### ISSUE TITLE
sstable::table::tests::test_build_empty_table fails

### ISSUE THREAD

**Issue by Fullstop000** [Fullstop000/wickdb#13]
```
failures:

---- sstable::table::tests::test_build_empty_table stdout ----
thread 'sstable::table::tests::test_build_empty_table' panicked at 'assertion failed: table.meta_block_handle.is_some()', src/sstable/table.rs:665:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:208
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::sync::once::Once::is_completed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:408
   6: wickdb::sstable::table::tests::test_build_empty_table
             at src/sstable/table.rs:665
   7: wickdb::sstable::table::tests::test_build_empty_table::{{closure}}
             at src/sstable/table.rs:655
   8: core::ops::function::FnOnce::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/ops/function.rs:231
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/liballoc/boxed.rs:704
  10: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  11: test::run_test::run_test_inner::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:272
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panic.rs:394
             at src/libtest/lib.rs:1468
```

Something wrong happens in table iterator

**Comment by Fullstop000** [comment]
Fixed by https://github.com/Fullstop000/wickdb/commit/f44198368efce744e37f460f2c775ebe41f52613
