### ISSUE TITLE
Potential CI issue in macOS

### ISSUE THREAD

**Issue by Fullstop000** [Fullstop000/wickdb#14]
https://travis-ci.org/Fullstop000/wickdb/jobs/588278442
CI failed in macOS because of the lack of lib `six` for `lldb`:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
ImportError: No module named six
Traceback (most recent call last):
  File "<string>", line 1, in <module>
```

And it's wired that `sstable::tests::test_simple_empty_key` hangs when running `kcov` but works fine in other places.

Relative issue: https://github.com/rust-lang/rust/issues/38380

**Comment by Fullstop000** [comment]
Fixed by https://github.com/Fullstop000/wickdb/commit/2d5e755b6aaccb146dac315fbc1f360eeb4ada93
